//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: ProtoDemo.proto
//
//// Protobuf Java Version: 3.25.1
//package com.fish.protobuf.entity;
//
//public final class ProtoDemo {
//  private ProtoDemo() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface StudentOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:Student)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>int32 id = 1;</code>
//     * @return The id.
//     */
//    int getId();
//
//    /**
//     * <code>string name = 2;</code>
//     * @return The name.
//     */
//    java.lang.String getName();
//    /**
//     * <code>string name = 2;</code>
//     * @return The bytes for name.
//     */
//    com.google.protobuf.ByteString
//        getNameBytes();
//
//    /**
//     * <code>string email = 3;</code>
//     * @return The email.
//     */
//    java.lang.String getEmail();
//    /**
//     * <code>string email = 3;</code>
//     * @return The bytes for email.
//     */
//    com.google.protobuf.ByteString
//        getEmailBytes();
//
//    /**
//     * <code>.Student.Sex sex = 4;</code>
//     * @return The enum numeric value on the wire for sex.
//     */
//    int getSexValue();
//    /**
//     * <code>.Student.Sex sex = 4;</code>
//     * @return The sex.
//     */
//    com.fish.protobuf.entity.ProtoDemo.Student.Sex getSex();
//
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    java.util.List<com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber>
//        getPhoneList();
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber getPhone(int index);
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    int getPhoneCount();
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    java.util.List<? extends com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder>
//        getPhoneOrBuilderList();
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(
//        int index);
//  }
//  /**
//   * Protobuf type {@code Student}
//   */
//  public static final class Student extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:Student)
//      StudentOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use Student.newBuilder() to construct.
//    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private Student() {
//      name_ = "";
//      email_ = "";
//      sex_ = 0;
//      phone_ = java.util.Collections.emptyList();
//    }
//
//    @java.lang.Override
//    @SuppressWarnings({"unused"})
//    protected java.lang.Object newInstance(
//        UnusedPrivateParameter unused) {
//      return new Student();
//    }
//
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_descriptor;
//    }
//
//    @java.lang.Override
//    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.fish.protobuf.entity.ProtoDemo.Student.class, com.fish.protobuf.entity.ProtoDemo.Student.Builder.class);
//    }
//
//    /**
//     * Protobuf enum {@code Student.Sex}
//     */
//    public enum Sex
//        implements com.google.protobuf.ProtocolMessageEnum {
//      /**
//       * <code>MAN = 0;</code>
//       */
//      MAN(0),
//      /**
//       * <code>WOMAN = 1;</code>
//       */
//      WOMAN(1),
//      UNRECOGNIZED(-1),
//      ;
//
//      /**
//       * <code>MAN = 0;</code>
//       */
//      public static final int MAN_VALUE = 0;
//      /**
//       * <code>WOMAN = 1;</code>
//       */
//      public static final int WOMAN_VALUE = 1;
//
//
//      public final int getNumber() {
//        if (this == UNRECOGNIZED) {
//          throw new java.lang.IllegalArgumentException(
//              "Can't get the number of an unknown enum value.");
//        }
//        return value;
//      }
//
//      /**
//       * @param value The numeric wire value of the corresponding enum entry.
//       * @return The enum associated with the given numeric wire value.
//       * @deprecated Use {@link #forNumber(int)} instead.
//       */
//      @java.lang.Deprecated
//      public static Sex valueOf(int value) {
//        return forNumber(value);
//      }
//
//      /**
//       * @param value The numeric wire value of the corresponding enum entry.
//       * @return The enum associated with the given numeric wire value.
//       */
//      public static Sex forNumber(int value) {
//        switch (value) {
//          case 0: return MAN;
//          case 1: return WOMAN;
//          default: return null;
//        }
//      }
//
//      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
//          internalGetValueMap() {
//        return internalValueMap;
//      }
//      private static final com.google.protobuf.Internal.EnumLiteMap<
//          Sex> internalValueMap =
//            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
//              public Sex findValueByNumber(int number) {
//                return Sex.forNumber(number);
//              }
//            };
//
//      public final com.google.protobuf.Descriptors.EnumValueDescriptor
//          getValueDescriptor() {
//        if (this == UNRECOGNIZED) {
//          throw new java.lang.IllegalStateException(
//              "Can't get the descriptor of an unrecognized enum value.");
//        }
//        return getDescriptor().getValues().get(ordinal());
//      }
//      public final com.google.protobuf.Descriptors.EnumDescriptor
//          getDescriptorForType() {
//        return getDescriptor();
//      }
//      public static final com.google.protobuf.Descriptors.EnumDescriptor
//          getDescriptor() {
//        return com.fish.protobuf.entity.ProtoDemo.Student.getDescriptor().getEnumTypes().get(0);
//      }
//
//      private static final Sex[] VALUES = values();
//
//      public static Sex valueOf(
//          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
//        if (desc.getType() != getDescriptor()) {
//          throw new java.lang.IllegalArgumentException(
//            "EnumValueDescriptor is not for this type.");
//        }
//        if (desc.getIndex() == -1) {
//          return UNRECOGNIZED;
//        }
//        return VALUES[desc.getIndex()];
//      }
//
//      private final int value;
//
//      private Sex(int value) {
//        this.value = value;
//      }
//
//      // @@protoc_insertion_point(enum_scope:Student.Sex)
//    }
//
//    /**
//     * Protobuf enum {@code Student.PhoneType}
//     */
//    public enum PhoneType
//        implements com.google.protobuf.ProtocolMessageEnum {
//      /**
//       * <code>MOBILE = 0;</code>
//       */
//      MOBILE(0),
//      /**
//       * <code>HOME = 1;</code>
//       */
//      HOME(1),
//      /**
//       * <code>WORK = 2;</code>
//       */
//      WORK(2),
//      UNRECOGNIZED(-1),
//      ;
//
//      /**
//       * <code>MOBILE = 0;</code>
//       */
//      public static final int MOBILE_VALUE = 0;
//      /**
//       * <code>HOME = 1;</code>
//       */
//      public static final int HOME_VALUE = 1;
//      /**
//       * <code>WORK = 2;</code>
//       */
//      public static final int WORK_VALUE = 2;
//
//
//      public final int getNumber() {
//        if (this == UNRECOGNIZED) {
//          throw new java.lang.IllegalArgumentException(
//              "Can't get the number of an unknown enum value.");
//        }
//        return value;
//      }
//
//      /**
//       * @param value The numeric wire value of the corresponding enum entry.
//       * @return The enum associated with the given numeric wire value.
//       * @deprecated Use {@link #forNumber(int)} instead.
//       */
//      @java.lang.Deprecated
//      public static PhoneType valueOf(int value) {
//        return forNumber(value);
//      }
//
//      /**
//       * @param value The numeric wire value of the corresponding enum entry.
//       * @return The enum associated with the given numeric wire value.
//       */
//      public static PhoneType forNumber(int value) {
//        switch (value) {
//          case 0: return MOBILE;
//          case 1: return HOME;
//          case 2: return WORK;
//          default: return null;
//        }
//      }
//
//      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
//          internalGetValueMap() {
//        return internalValueMap;
//      }
//      private static final com.google.protobuf.Internal.EnumLiteMap<
//          PhoneType> internalValueMap =
//            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
//              public PhoneType findValueByNumber(int number) {
//                return PhoneType.forNumber(number);
//              }
//            };
//
//      public final com.google.protobuf.Descriptors.EnumValueDescriptor
//          getValueDescriptor() {
//        if (this == UNRECOGNIZED) {
//          throw new java.lang.IllegalStateException(
//              "Can't get the descriptor of an unrecognized enum value.");
//        }
//        return getDescriptor().getValues().get(ordinal());
//      }
//      public final com.google.protobuf.Descriptors.EnumDescriptor
//          getDescriptorForType() {
//        return getDescriptor();
//      }
//      public static final com.google.protobuf.Descriptors.EnumDescriptor
//          getDescriptor() {
//        return com.fish.protobuf.entity.ProtoDemo.Student.getDescriptor().getEnumTypes().get(1);
//      }
//
//      private static final PhoneType[] VALUES = values();
//
//      public static PhoneType valueOf(
//          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
//        if (desc.getType() != getDescriptor()) {
//          throw new java.lang.IllegalArgumentException(
//            "EnumValueDescriptor is not for this type.");
//        }
//        if (desc.getIndex() == -1) {
//          return UNRECOGNIZED;
//        }
//        return VALUES[desc.getIndex()];
//      }
//
//      private final int value;
//
//      private PhoneType(int value) {
//        this.value = value;
//      }
//
//      // @@protoc_insertion_point(enum_scope:Student.PhoneType)
//    }
//
//    public interface PhoneNumberOrBuilder extends
//        // @@protoc_insertion_point(interface_extends:Student.PhoneNumber)
//        com.google.protobuf.MessageOrBuilder {
//
//      /**
//       * <code>string number = 1;</code>
//       * @return The number.
//       */
//      java.lang.String getNumber();
//      /**
//       * <code>string number = 1;</code>
//       * @return The bytes for number.
//       */
//      com.google.protobuf.ByteString
//          getNumberBytes();
//
//      /**
//       * <code>.Student.PhoneType type = 2;</code>
//       * @return The enum numeric value on the wire for type.
//       */
//      int getTypeValue();
//      /**
//       * <code>.Student.PhoneType type = 2;</code>
//       * @return The type.
//       */
//      com.fish.protobuf.entity.ProtoDemo.Student.PhoneType getType();
//    }
//    /**
//     * Protobuf type {@code Student.PhoneNumber}
//     */
//    public static final class PhoneNumber extends
//        com.google.protobuf.GeneratedMessageV3 implements
//        // @@protoc_insertion_point(message_implements:Student.PhoneNumber)
//        PhoneNumberOrBuilder {
//    private static final long serialVersionUID = 0L;
//      // Use PhoneNumber.newBuilder() to construct.
//      private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//        super(builder);
//      }
//      private PhoneNumber() {
//        number_ = "";
//        type_ = 0;
//      }
//
//      @java.lang.Override
//      @SuppressWarnings({"unused"})
//      protected java.lang.Object newInstance(
//          UnusedPrivateParameter unused) {
//        return new PhoneNumber();
//      }
//
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_PhoneNumber_descriptor;
//      }
//
//      @java.lang.Override
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_PhoneNumber_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.class, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder.class);
//      }
//
//      public static final int NUMBER_FIELD_NUMBER = 1;
//      @SuppressWarnings("serial")
//      private volatile java.lang.Object number_ = "";
//      /**
//       * <code>string number = 1;</code>
//       * @return The number.
//       */
//      @java.lang.Override
//      public java.lang.String getNumber() {
//        java.lang.Object ref = number_;
//        if (ref instanceof java.lang.String) {
//          return (java.lang.String) ref;
//        } else {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          number_ = s;
//          return s;
//        }
//      }
//      /**
//       * <code>string number = 1;</code>
//       * @return The bytes for number.
//       */
//      @java.lang.Override
//      public com.google.protobuf.ByteString
//          getNumberBytes() {
//        java.lang.Object ref = number_;
//        if (ref instanceof java.lang.String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          number_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//
//      public static final int TYPE_FIELD_NUMBER = 2;
//      private int type_ = 0;
//      /**
//       * <code>.Student.PhoneType type = 2;</code>
//       * @return The enum numeric value on the wire for type.
//       */
//      @java.lang.Override public int getTypeValue() {
//        return type_;
//      }
//      /**
//       * <code>.Student.PhoneType type = 2;</code>
//       * @return The type.
//       */
//      @java.lang.Override public com.fish.protobuf.entity.ProtoDemo.Student.PhoneType getType() {
//        com.fish.protobuf.entity.ProtoDemo.Student.PhoneType result = com.fish.protobuf.entity.ProtoDemo.Student.PhoneType.forNumber(type_);
//        return result == null ? com.fish.protobuf.entity.ProtoDemo.Student.PhoneType.UNRECOGNIZED : result;
//      }
//
//      private byte memoizedIsInitialized = -1;
//      @java.lang.Override
//      public final boolean isInitialized() {
//        byte isInitialized = memoizedIsInitialized;
//        if (isInitialized == 1) return true;
//        if (isInitialized == 0) return false;
//
//        memoizedIsInitialized = 1;
//        return true;
//      }
//
//      @java.lang.Override
//      public void writeTo(com.google.protobuf.CodedOutputStream output)
//                          throws java.io.IOException {
//        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
//          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
//        }
//        if (type_ != com.fish.protobuf.entity.ProtoDemo.Student.PhoneType.MOBILE.getNumber()) {
//          output.writeEnum(2, type_);
//        }
//        getUnknownFields().writeTo(output);
//      }
//
//      @java.lang.Override
//      public int getSerializedSize() {
//        int size = memoizedSize;
//        if (size != -1) return size;
//
//        size = 0;
//        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
//          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
//        }
//        if (type_ != com.fish.protobuf.entity.ProtoDemo.Student.PhoneType.MOBILE.getNumber()) {
//          size += com.google.protobuf.CodedOutputStream
//            .computeEnumSize(2, type_);
//        }
//        size += getUnknownFields().getSerializedSize();
//        memoizedSize = size;
//        return size;
//      }
//
//      @java.lang.Override
//      public boolean equals(final java.lang.Object obj) {
//        if (obj == this) {
//         return true;
//        }
//        if (!(obj instanceof com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber)) {
//          return super.equals(obj);
//        }
//        com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber other = (com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber) obj;
//
//        if (!getNumber()
//            .equals(other.getNumber())) return false;
//        if (type_ != other.type_) return false;
//        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
//        return true;
//      }
//
//      @java.lang.Override
//      public int hashCode() {
//        if (memoizedHashCode != 0) {
//          return memoizedHashCode;
//        }
//        int hash = 41;
//        hash = (19 * hash) + getDescriptor().hashCode();
//        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
//        hash = (53 * hash) + getNumber().hashCode();
//        hash = (37 * hash) + TYPE_FIELD_NUMBER;
//        hash = (53 * hash) + type_;
//        hash = (29 * hash) + getUnknownFields().hashCode();
//        memoizedHashCode = hash;
//        return hash;
//      }
//
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(
//          java.nio.ByteBuffer data)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data);
//      }
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(
//          java.nio.ByteBuffer data,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data, extensionRegistry);
//      }
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(
//          com.google.protobuf.ByteString data)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data);
//      }
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(
//          com.google.protobuf.ByteString data,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data, extensionRegistry);
//      }
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(byte[] data)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data);
//      }
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(
//          byte[] data,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data, extensionRegistry);
//      }
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(java.io.InputStream input)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseWithIOException(PARSER, input);
//      }
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(
//          java.io.InputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseWithIOException(PARSER, input, extensionRegistry);
//      }
//
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseDelimitedWithIOException(PARSER, input);
//      }
//
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseDelimitedFrom(
//          java.io.InputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//      }
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(
//          com.google.protobuf.CodedInputStream input)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseWithIOException(PARSER, input);
//      }
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber parseFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseWithIOException(PARSER, input, extensionRegistry);
//      }
//
//      @java.lang.Override
//      public Builder newBuilderForType() { return newBuilder(); }
//      public static Builder newBuilder() {
//        return DEFAULT_INSTANCE.toBuilder();
//      }
//      public static Builder newBuilder(com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber prototype) {
//        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//      }
//      @java.lang.Override
//      public Builder toBuilder() {
//        return this == DEFAULT_INSTANCE
//            ? new Builder() : new Builder().mergeFrom(this);
//      }
//
//      @java.lang.Override
//      protected Builder newBuilderForType(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        Builder builder = new Builder(parent);
//        return builder;
//      }
//      /**
//       * Protobuf type {@code Student.PhoneNumber}
//       */
//      public static final class Builder extends
//          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//          // @@protoc_insertion_point(builder_implements:Student.PhoneNumber)
//          com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder {
//        public static final com.google.protobuf.Descriptors.Descriptor
//            getDescriptor() {
//          return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_PhoneNumber_descriptor;
//        }
//
//        @java.lang.Override
//        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//            internalGetFieldAccessorTable() {
//          return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_PhoneNumber_fieldAccessorTable
//              .ensureFieldAccessorsInitialized(
//                  com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.class, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder.class);
//        }
//
//        // Construct using com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.newBuilder()
//        private Builder() {
//
//        }
//
//        private Builder(
//            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//          super(parent);
//
//        }
//        @java.lang.Override
//        public Builder clear() {
//          super.clear();
//          bitField0_ = 0;
//          number_ = "";
//          type_ = 0;
//          return this;
//        }
//
//        @java.lang.Override
//        public com.google.protobuf.Descriptors.Descriptor
//            getDescriptorForType() {
//          return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_PhoneNumber_descriptor;
//        }
//
//        @java.lang.Override
//        public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber getDefaultInstanceForType() {
//          return com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.getDefaultInstance();
//        }
//
//        @java.lang.Override
//        public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber build() {
//          com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber result = buildPartial();
//          if (!result.isInitialized()) {
//            throw newUninitializedMessageException(result);
//          }
//          return result;
//        }
//
//        @java.lang.Override
//        public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber buildPartial() {
//          com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber result = new com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber(this);
//          if (bitField0_ != 0) { buildPartial0(result); }
//          onBuilt();
//          return result;
//        }
//
//        private void buildPartial0(com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber result) {
//          int from_bitField0_ = bitField0_;
//          if (((from_bitField0_ & 0x00000001) != 0)) {
//            result.number_ = number_;
//          }
//          if (((from_bitField0_ & 0x00000002) != 0)) {
//            result.type_ = type_;
//          }
//        }
//
//        @java.lang.Override
//        public Builder clone() {
//          return super.clone();
//        }
//        @java.lang.Override
//        public Builder setField(
//            com.google.protobuf.Descriptors.FieldDescriptor field,
//            java.lang.Object value) {
//          return super.setField(field, value);
//        }
//        @java.lang.Override
//        public Builder clearField(
//            com.google.protobuf.Descriptors.FieldDescriptor field) {
//          return super.clearField(field);
//        }
//        @java.lang.Override
//        public Builder clearOneof(
//            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//          return super.clearOneof(oneof);
//        }
//        @java.lang.Override
//        public Builder setRepeatedField(
//            com.google.protobuf.Descriptors.FieldDescriptor field,
//            int index, java.lang.Object value) {
//          return super.setRepeatedField(field, index, value);
//        }
//        @java.lang.Override
//        public Builder addRepeatedField(
//            com.google.protobuf.Descriptors.FieldDescriptor field,
//            java.lang.Object value) {
//          return super.addRepeatedField(field, value);
//        }
//        @java.lang.Override
//        public Builder mergeFrom(com.google.protobuf.Message other) {
//          if (other instanceof com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber) {
//            return mergeFrom((com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber)other);
//          } else {
//            super.mergeFrom(other);
//            return this;
//          }
//        }
//
//        public Builder mergeFrom(com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber other) {
//          if (other == com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.getDefaultInstance()) return this;
//          if (!other.getNumber().isEmpty()) {
//            number_ = other.number_;
//            bitField0_ |= 0x00000001;
//            onChanged();
//          }
//          if (other.type_ != 0) {
//            setTypeValue(other.getTypeValue());
//          }
//          this.mergeUnknownFields(other.getUnknownFields());
//          onChanged();
//          return this;
//        }
//
//        @java.lang.Override
//        public final boolean isInitialized() {
//          return true;
//        }
//
//        @java.lang.Override
//        public Builder mergeFrom(
//            com.google.protobuf.CodedInputStream input,
//            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//            throws java.io.IOException {
//          if (extensionRegistry == null) {
//            throw new java.lang.NullPointerException();
//          }
//          try {
//            boolean done = false;
//            while (!done) {
//              int tag = input.readTag();
//              switch (tag) {
//                case 0:
//                  done = true;
//                  break;
//                case 10: {
//                  number_ = input.readStringRequireUtf8();
//                  bitField0_ |= 0x00000001;
//                  break;
//                } // case 10
//                case 16: {
//                  type_ = input.readEnum();
//                  bitField0_ |= 0x00000002;
//                  break;
//                } // case 16
//                default: {
//                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                    done = true; // was an endgroup tag
//                  }
//                  break;
//                } // default:
//              } // switch (tag)
//            } // while (!done)
//          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//            throw e.unwrapIOException();
//          } finally {
//            onChanged();
//          } // finally
//          return this;
//        }
//        private int bitField0_;
//
//        private java.lang.Object number_ = "";
//        /**
//         * <code>string number = 1;</code>
//         * @return The number.
//         */
//        public java.lang.String getNumber() {
//          java.lang.Object ref = number_;
//          if (!(ref instanceof java.lang.String)) {
//            com.google.protobuf.ByteString bs =
//                (com.google.protobuf.ByteString) ref;
//            java.lang.String s = bs.toStringUtf8();
//            number_ = s;
//            return s;
//          } else {
//            return (java.lang.String) ref;
//          }
//        }
//        /**
//         * <code>string number = 1;</code>
//         * @return The bytes for number.
//         */
//        public com.google.protobuf.ByteString
//            getNumberBytes() {
//          java.lang.Object ref = number_;
//          if (ref instanceof String) {
//            com.google.protobuf.ByteString b =
//                com.google.protobuf.ByteString.copyFromUtf8(
//                    (java.lang.String) ref);
//            number_ = b;
//            return b;
//          } else {
//            return (com.google.protobuf.ByteString) ref;
//          }
//        }
//        /**
//         * <code>string number = 1;</code>
//         * @param value The number to set.
//         * @return This builder for chaining.
//         */
//        public Builder setNumber(
//            java.lang.String value) {
//          if (value == null) { throw new NullPointerException(); }
//          number_ = value;
//          bitField0_ |= 0x00000001;
//          onChanged();
//          return this;
//        }
//        /**
//         * <code>string number = 1;</code>
//         * @return This builder for chaining.
//         */
//        public Builder clearNumber() {
//          number_ = getDefaultInstance().getNumber();
//          bitField0_ = (bitField0_ & ~0x00000001);
//          onChanged();
//          return this;
//        }
//        /**
//         * <code>string number = 1;</code>
//         * @param value The bytes for number to set.
//         * @return This builder for chaining.
//         */
//        public Builder setNumberBytes(
//            com.google.protobuf.ByteString value) {
//          if (value == null) { throw new NullPointerException(); }
//          checkByteStringIsUtf8(value);
//          number_ = value;
//          bitField0_ |= 0x00000001;
//          onChanged();
//          return this;
//        }
//
//        private int type_ = 0;
//        /**
//         * <code>.Student.PhoneType type = 2;</code>
//         * @return The enum numeric value on the wire for type.
//         */
//        @java.lang.Override public int getTypeValue() {
//          return type_;
//        }
//        /**
//         * <code>.Student.PhoneType type = 2;</code>
//         * @param value The enum numeric value on the wire for type to set.
//         * @return This builder for chaining.
//         */
//        public Builder setTypeValue(int value) {
//          type_ = value;
//          bitField0_ |= 0x00000002;
//          onChanged();
//          return this;
//        }
//        /**
//         * <code>.Student.PhoneType type = 2;</code>
//         * @return The type.
//         */
//        @java.lang.Override
//        public com.fish.protobuf.entity.ProtoDemo.Student.PhoneType getType() {
//          com.fish.protobuf.entity.ProtoDemo.Student.PhoneType result = com.fish.protobuf.entity.ProtoDemo.Student.PhoneType.forNumber(type_);
//          return result == null ? com.fish.protobuf.entity.ProtoDemo.Student.PhoneType.UNRECOGNIZED : result;
//        }
//        /**
//         * <code>.Student.PhoneType type = 2;</code>
//         * @param value The type to set.
//         * @return This builder for chaining.
//         */
//        public Builder setType(com.fish.protobuf.entity.ProtoDemo.Student.PhoneType value) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          bitField0_ |= 0x00000002;
//          type_ = value.getNumber();
//          onChanged();
//          return this;
//        }
//        /**
//         * <code>.Student.PhoneType type = 2;</code>
//         * @return This builder for chaining.
//         */
//        public Builder clearType() {
//          bitField0_ = (bitField0_ & ~0x00000002);
//          type_ = 0;
//          onChanged();
//          return this;
//        }
//        @java.lang.Override
//        public final Builder setUnknownFields(
//            final com.google.protobuf.UnknownFieldSet unknownFields) {
//          return super.setUnknownFields(unknownFields);
//        }
//
//        @java.lang.Override
//        public final Builder mergeUnknownFields(
//            final com.google.protobuf.UnknownFieldSet unknownFields) {
//          return super.mergeUnknownFields(unknownFields);
//        }
//
//
//        // @@protoc_insertion_point(builder_scope:Student.PhoneNumber)
//      }
//
//      // @@protoc_insertion_point(class_scope:Student.PhoneNumber)
//      private static final com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber DEFAULT_INSTANCE;
//      static {
//        DEFAULT_INSTANCE = new com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber();
//      }
//
//      public static com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber getDefaultInstance() {
//        return DEFAULT_INSTANCE;
//      }
//
//      private static final com.google.protobuf.Parser<PhoneNumber>
//          PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
//        @java.lang.Override
//        public PhoneNumber parsePartialFrom(
//            com.google.protobuf.CodedInputStream input,
//            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//            throws com.google.protobuf.InvalidProtocolBufferException {
//          Builder builder = newBuilder();
//          try {
//            builder.mergeFrom(input, extensionRegistry);
//          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//            throw e.setUnfinishedMessage(builder.buildPartial());
//          } catch (com.google.protobuf.UninitializedMessageException e) {
//            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
//          } catch (java.io.IOException e) {
//            throw new com.google.protobuf.InvalidProtocolBufferException(e)
//                .setUnfinishedMessage(builder.buildPartial());
//          }
//          return builder.buildPartial();
//        }
//      };
//
//      public static com.google.protobuf.Parser<PhoneNumber> parser() {
//        return PARSER;
//      }
//
//      @java.lang.Override
//      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
//        return PARSER;
//      }
//
//      @java.lang.Override
//      public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber getDefaultInstanceForType() {
//        return DEFAULT_INSTANCE;
//      }
//
//    }
//
//    public static final int ID_FIELD_NUMBER = 1;
//    private int id_ = 0;
//    /**
//     * <code>int32 id = 1;</code>
//     * @return The id.
//     */
//    @java.lang.Override
//    public int getId() {
//      return id_;
//    }
//
//    public static final int NAME_FIELD_NUMBER = 2;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object name_ = "";
//    /**
//     * <code>string name = 2;</code>
//     * @return The name.
//     */
//    @java.lang.Override
//    public java.lang.String getName() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        name_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string name = 2;</code>
//     * @return The bytes for name.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getNameBytes() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        name_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int EMAIL_FIELD_NUMBER = 3;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object email_ = "";
//    /**
//     * <code>string email = 3;</code>
//     * @return The email.
//     */
//    @java.lang.Override
//    public java.lang.String getEmail() {
//      java.lang.Object ref = email_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        email_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string email = 3;</code>
//     * @return The bytes for email.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getEmailBytes() {
//      java.lang.Object ref = email_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        email_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int SEX_FIELD_NUMBER = 4;
//    private int sex_ = 0;
//    /**
//     * <code>.Student.Sex sex = 4;</code>
//     * @return The enum numeric value on the wire for sex.
//     */
//    @java.lang.Override public int getSexValue() {
//      return sex_;
//    }
//    /**
//     * <code>.Student.Sex sex = 4;</code>
//     * @return The sex.
//     */
//    @java.lang.Override public com.fish.protobuf.entity.ProtoDemo.Student.Sex getSex() {
//      com.fish.protobuf.entity.ProtoDemo.Student.Sex result = com.fish.protobuf.entity.ProtoDemo.Student.Sex.forNumber(sex_);
//      return result == null ? com.fish.protobuf.entity.ProtoDemo.Student.Sex.UNRECOGNIZED : result;
//    }
//
//    public static final int PHONE_FIELD_NUMBER = 5;
//    @SuppressWarnings("serial")
//    private java.util.List<com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber> phone_;
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    @java.lang.Override
//    public java.util.List<com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber> getPhoneList() {
//      return phone_;
//    }
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    @java.lang.Override
//    public java.util.List<? extends com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder>
//        getPhoneOrBuilderList() {
//      return phone_;
//    }
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    @java.lang.Override
//    public int getPhoneCount() {
//      return phone_.size();
//    }
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    @java.lang.Override
//    public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber getPhone(int index) {
//      return phone_.get(index);
//    }
//    /**
//     * <code>repeated .Student.PhoneNumber phone = 5;</code>
//     */
//    @java.lang.Override
//    public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(
//        int index) {
//      return phone_.get(index);
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @java.lang.Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @java.lang.Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (id_ != 0) {
//        output.writeInt32(1, id_);
//      }
//      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
//      }
//      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
//      }
//      if (sex_ != com.fish.protobuf.entity.ProtoDemo.Student.Sex.MAN.getNumber()) {
//        output.writeEnum(4, sex_);
//      }
//      for (int i = 0; i < phone_.size(); i++) {
//        output.writeMessage(5, phone_.get(i));
//      }
//      getUnknownFields().writeTo(output);
//    }
//
//    @java.lang.Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (id_ != 0) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(1, id_);
//      }
//      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
//      }
//      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
//      }
//      if (sex_ != com.fish.protobuf.entity.ProtoDemo.Student.Sex.MAN.getNumber()) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeEnumSize(4, sex_);
//      }
//      for (int i = 0; i < phone_.size(); i++) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeMessageSize(5, phone_.get(i));
//      }
//      size += getUnknownFields().getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @java.lang.Override
//    public boolean equals(final java.lang.Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof com.fish.protobuf.entity.ProtoDemo.Student)) {
//        return super.equals(obj);
//      }
//      com.fish.protobuf.entity.ProtoDemo.Student other = (com.fish.protobuf.entity.ProtoDemo.Student) obj;
//
//      if (getId()
//          != other.getId()) return false;
//      if (!getName()
//          .equals(other.getName())) return false;
//      if (!getEmail()
//          .equals(other.getEmail())) return false;
//      if (sex_ != other.sex_) return false;
//      if (!getPhoneList()
//          .equals(other.getPhoneList())) return false;
//      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
//      return true;
//    }
//
//    @java.lang.Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + ID_FIELD_NUMBER;
//      hash = (53 * hash) + getId();
//      hash = (37 * hash) + NAME_FIELD_NUMBER;
//      hash = (53 * hash) + getName().hashCode();
//      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
//      hash = (53 * hash) + getEmail().hashCode();
//      hash = (37 * hash) + SEX_FIELD_NUMBER;
//      hash = (53 * hash) + sex_;
//      if (getPhoneCount() > 0) {
//        hash = (37 * hash) + PHONE_FIELD_NUMBER;
//        hash = (53 * hash) + getPhoneList().hashCode();
//      }
//      hash = (29 * hash) + getUnknownFields().hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.fish.protobuf.entity.ProtoDemo.Student parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @java.lang.Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(com.fish.protobuf.entity.ProtoDemo.Student prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @java.lang.Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code Student}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:Student)
//        com.fish.protobuf.entity.ProtoDemo.StudentOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_descriptor;
//      }
//
//      @java.lang.Override
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.fish.protobuf.entity.ProtoDemo.Student.class, com.fish.protobuf.entity.ProtoDemo.Student.Builder.class);
//      }
//
//      // Construct using com.fish.protobuf.entity.ProtoDemo.Student.newBuilder()
//      private Builder() {
//
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//
//      }
//      @java.lang.Override
//      public Builder clear() {
//        super.clear();
//        bitField0_ = 0;
//        id_ = 0;
//        name_ = "";
//        email_ = "";
//        sex_ = 0;
//        if (phoneBuilder_ == null) {
//          phone_ = java.util.Collections.emptyList();
//        } else {
//          phone_ = null;
//          phoneBuilder_.clear();
//        }
//        bitField0_ = (bitField0_ & ~0x00000010);
//        return this;
//      }
//
//      @java.lang.Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.fish.protobuf.entity.ProtoDemo.internal_static_Student_descriptor;
//      }
//
//      @java.lang.Override
//      public com.fish.protobuf.entity.ProtoDemo.Student getDefaultInstanceForType() {
//        return com.fish.protobuf.entity.ProtoDemo.Student.getDefaultInstance();
//      }
//
//      @java.lang.Override
//      public com.fish.protobuf.entity.ProtoDemo.Student build() {
//        com.fish.protobuf.entity.ProtoDemo.Student result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @java.lang.Override
//      public com.fish.protobuf.entity.ProtoDemo.Student buildPartial() {
//        com.fish.protobuf.entity.ProtoDemo.Student result = new com.fish.protobuf.entity.ProtoDemo.Student(this);
//        buildPartialRepeatedFields(result);
//        if (bitField0_ != 0) { buildPartial0(result); }
//        onBuilt();
//        return result;
//      }
//
//      private void buildPartialRepeatedFields(com.fish.protobuf.entity.ProtoDemo.Student result) {
//        if (phoneBuilder_ == null) {
//          if (((bitField0_ & 0x00000010) != 0)) {
//            phone_ = java.util.Collections.unmodifiableList(phone_);
//            bitField0_ = (bitField0_ & ~0x00000010);
//          }
//          result.phone_ = phone_;
//        } else {
//          result.phone_ = phoneBuilder_.build();
//        }
//      }
//
//      private void buildPartial0(com.fish.protobuf.entity.ProtoDemo.Student result) {
//        int from_bitField0_ = bitField0_;
//        if (((from_bitField0_ & 0x00000001) != 0)) {
//          result.id_ = id_;
//        }
//        if (((from_bitField0_ & 0x00000002) != 0)) {
//          result.name_ = name_;
//        }
//        if (((from_bitField0_ & 0x00000004) != 0)) {
//          result.email_ = email_;
//        }
//        if (((from_bitField0_ & 0x00000008) != 0)) {
//          result.sex_ = sex_;
//        }
//      }
//
//      @java.lang.Override
//      public Builder clone() {
//        return super.clone();
//      }
//      @java.lang.Override
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return super.setField(field, value);
//      }
//      @java.lang.Override
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return super.clearField(field);
//      }
//      @java.lang.Override
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return super.clearOneof(oneof);
//      }
//      @java.lang.Override
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, java.lang.Object value) {
//        return super.setRepeatedField(field, index, value);
//      }
//      @java.lang.Override
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return super.addRepeatedField(field, value);
//      }
//      @java.lang.Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof com.fish.protobuf.entity.ProtoDemo.Student) {
//          return mergeFrom((com.fish.protobuf.entity.ProtoDemo.Student)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.fish.protobuf.entity.ProtoDemo.Student other) {
//        if (other == com.fish.protobuf.entity.ProtoDemo.Student.getDefaultInstance()) return this;
//        if (other.getId() != 0) {
//          setId(other.getId());
//        }
//        if (!other.getName().isEmpty()) {
//          name_ = other.name_;
//          bitField0_ |= 0x00000002;
//          onChanged();
//        }
//        if (!other.getEmail().isEmpty()) {
//          email_ = other.email_;
//          bitField0_ |= 0x00000004;
//          onChanged();
//        }
//        if (other.sex_ != 0) {
//          setSexValue(other.getSexValue());
//        }
//        if (phoneBuilder_ == null) {
//          if (!other.phone_.isEmpty()) {
//            if (phone_.isEmpty()) {
//              phone_ = other.phone_;
//              bitField0_ = (bitField0_ & ~0x00000010);
//            } else {
//              ensurePhoneIsMutable();
//              phone_.addAll(other.phone_);
//            }
//            onChanged();
//          }
//        } else {
//          if (!other.phone_.isEmpty()) {
//            if (phoneBuilder_.isEmpty()) {
//              phoneBuilder_.dispose();
//              phoneBuilder_ = null;
//              phone_ = other.phone_;
//              bitField0_ = (bitField0_ & ~0x00000010);
//              phoneBuilder_ =
//                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
//                   getPhoneFieldBuilder() : null;
//            } else {
//              phoneBuilder_.addAllMessages(other.phone_);
//            }
//          }
//        }
//        this.mergeUnknownFields(other.getUnknownFields());
//        onChanged();
//        return this;
//      }
//
//      @java.lang.Override
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        if (extensionRegistry == null) {
//          throw new java.lang.NullPointerException();
//        }
//        try {
//          boolean done = false;
//          while (!done) {
//            int tag = input.readTag();
//            switch (tag) {
//              case 0:
//                done = true;
//                break;
//              case 8: {
//                id_ = input.readInt32();
//                bitField0_ |= 0x00000001;
//                break;
//              } // case 8
//              case 18: {
//                name_ = input.readStringRequireUtf8();
//                bitField0_ |= 0x00000002;
//                break;
//              } // case 18
//              case 26: {
//                email_ = input.readStringRequireUtf8();
//                bitField0_ |= 0x00000004;
//                break;
//              } // case 26
//              case 32: {
//                sex_ = input.readEnum();
//                bitField0_ |= 0x00000008;
//                break;
//              } // case 32
//              case 42: {
//                com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber m =
//                    input.readMessage(
//                        com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.parser(),
//                        extensionRegistry);
//                if (phoneBuilder_ == null) {
//                  ensurePhoneIsMutable();
//                  phone_.add(m);
//                } else {
//                  phoneBuilder_.addMessage(m);
//                }
//                break;
//              } // case 42
//              default: {
//                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                  done = true; // was an endgroup tag
//                }
//                break;
//              } // default:
//            } // switch (tag)
//          } // while (!done)
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          throw e.unwrapIOException();
//        } finally {
//          onChanged();
//        } // finally
//        return this;
//      }
//      private int bitField0_;
//
//      private int id_ ;
//      /**
//       * <code>int32 id = 1;</code>
//       * @return The id.
//       */
//      @java.lang.Override
//      public int getId() {
//        return id_;
//      }
//      /**
//       * <code>int32 id = 1;</code>
//       * @param value The id to set.
//       * @return This builder for chaining.
//       */
//      public Builder setId(int value) {
//
//        id_ = value;
//        bitField0_ |= 0x00000001;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>int32 id = 1;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearId() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        id_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object name_ = "";
//      /**
//       * <code>string name = 2;</code>
//       * @return The name.
//       */
//      public java.lang.String getName() {
//        java.lang.Object ref = name_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          name_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @return The bytes for name.
//       */
//      public com.google.protobuf.ByteString
//          getNameBytes() {
//        java.lang.Object ref = name_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          name_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @param value The name to set.
//       * @return This builder for chaining.
//       */
//      public Builder setName(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        name_ = value;
//        bitField0_ |= 0x00000002;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearName() {
//        name_ = getDefaultInstance().getName();
//        bitField0_ = (bitField0_ & ~0x00000002);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @param value The bytes for name to set.
//       * @return This builder for chaining.
//       */
//      public Builder setNameBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        checkByteStringIsUtf8(value);
//        name_ = value;
//        bitField0_ |= 0x00000002;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object email_ = "";
//      /**
//       * <code>string email = 3;</code>
//       * @return The email.
//       */
//      public java.lang.String getEmail() {
//        java.lang.Object ref = email_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          email_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string email = 3;</code>
//       * @return The bytes for email.
//       */
//      public com.google.protobuf.ByteString
//          getEmailBytes() {
//        java.lang.Object ref = email_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          email_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string email = 3;</code>
//       * @param value The email to set.
//       * @return This builder for chaining.
//       */
//      public Builder setEmail(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        email_ = value;
//        bitField0_ |= 0x00000004;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string email = 3;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearEmail() {
//        email_ = getDefaultInstance().getEmail();
//        bitField0_ = (bitField0_ & ~0x00000004);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string email = 3;</code>
//       * @param value The bytes for email to set.
//       * @return This builder for chaining.
//       */
//      public Builder setEmailBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        checkByteStringIsUtf8(value);
//        email_ = value;
//        bitField0_ |= 0x00000004;
//        onChanged();
//        return this;
//      }
//
//      private int sex_ = 0;
//      /**
//       * <code>.Student.Sex sex = 4;</code>
//       * @return The enum numeric value on the wire for sex.
//       */
//      @java.lang.Override public int getSexValue() {
//        return sex_;
//      }
//      /**
//       * <code>.Student.Sex sex = 4;</code>
//       * @param value The enum numeric value on the wire for sex to set.
//       * @return This builder for chaining.
//       */
//      public Builder setSexValue(int value) {
//        sex_ = value;
//        bitField0_ |= 0x00000008;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>.Student.Sex sex = 4;</code>
//       * @return The sex.
//       */
//      @java.lang.Override
//      public com.fish.protobuf.entity.ProtoDemo.Student.Sex getSex() {
//        com.fish.protobuf.entity.ProtoDemo.Student.Sex result = com.fish.protobuf.entity.ProtoDemo.Student.Sex.forNumber(sex_);
//        return result == null ? com.fish.protobuf.entity.ProtoDemo.Student.Sex.UNRECOGNIZED : result;
//      }
//      /**
//       * <code>.Student.Sex sex = 4;</code>
//       * @param value The sex to set.
//       * @return This builder for chaining.
//       */
//      public Builder setSex(com.fish.protobuf.entity.ProtoDemo.Student.Sex value) {
//        if (value == null) {
//          throw new NullPointerException();
//        }
//        bitField0_ |= 0x00000008;
//        sex_ = value.getNumber();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>.Student.Sex sex = 4;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearSex() {
//        bitField0_ = (bitField0_ & ~0x00000008);
//        sex_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private java.util.List<com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber> phone_ =
//        java.util.Collections.emptyList();
//      private void ensurePhoneIsMutable() {
//        if (!((bitField0_ & 0x00000010) != 0)) {
//          phone_ = new java.util.ArrayList<com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber>(phone_);
//          bitField0_ |= 0x00000010;
//         }
//      }
//
//      private com.google.protobuf.RepeatedFieldBuilderV3<
//          com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder> phoneBuilder_;
//
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public java.util.List<com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber> getPhoneList() {
//        if (phoneBuilder_ == null) {
//          return java.util.Collections.unmodifiableList(phone_);
//        } else {
//          return phoneBuilder_.getMessageList();
//        }
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public int getPhoneCount() {
//        if (phoneBuilder_ == null) {
//          return phone_.size();
//        } else {
//          return phoneBuilder_.getCount();
//        }
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber getPhone(int index) {
//        if (phoneBuilder_ == null) {
//          return phone_.get(index);
//        } else {
//          return phoneBuilder_.getMessage(index);
//        }
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public Builder setPhone(
//          int index, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber value) {
//        if (phoneBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          ensurePhoneIsMutable();
//          phone_.set(index, value);
//          onChanged();
//        } else {
//          phoneBuilder_.setMessage(index, value);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public Builder setPhone(
//          int index, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder builderForValue) {
//        if (phoneBuilder_ == null) {
//          ensurePhoneIsMutable();
//          phone_.set(index, builderForValue.build());
//          onChanged();
//        } else {
//          phoneBuilder_.setMessage(index, builderForValue.build());
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public Builder addPhone(com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber value) {
//        if (phoneBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          ensurePhoneIsMutable();
//          phone_.add(value);
//          onChanged();
//        } else {
//          phoneBuilder_.addMessage(value);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public Builder addPhone(
//          int index, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber value) {
//        if (phoneBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          ensurePhoneIsMutable();
//          phone_.add(index, value);
//          onChanged();
//        } else {
//          phoneBuilder_.addMessage(index, value);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public Builder addPhone(
//          com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder builderForValue) {
//        if (phoneBuilder_ == null) {
//          ensurePhoneIsMutable();
//          phone_.add(builderForValue.build());
//          onChanged();
//        } else {
//          phoneBuilder_.addMessage(builderForValue.build());
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public Builder addPhone(
//          int index, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder builderForValue) {
//        if (phoneBuilder_ == null) {
//          ensurePhoneIsMutable();
//          phone_.add(index, builderForValue.build());
//          onChanged();
//        } else {
//          phoneBuilder_.addMessage(index, builderForValue.build());
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public Builder addAllPhone(
//          java.lang.Iterable<? extends com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber> values) {
//        if (phoneBuilder_ == null) {
//          ensurePhoneIsMutable();
//          com.google.protobuf.AbstractMessageLite.Builder.addAll(
//              values, phone_);
//          onChanged();
//        } else {
//          phoneBuilder_.addAllMessages(values);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public Builder clearPhone() {
//        if (phoneBuilder_ == null) {
//          phone_ = java.util.Collections.emptyList();
//          bitField0_ = (bitField0_ & ~0x00000010);
//          onChanged();
//        } else {
//          phoneBuilder_.clear();
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public Builder removePhone(int index) {
//        if (phoneBuilder_ == null) {
//          ensurePhoneIsMutable();
//          phone_.remove(index);
//          onChanged();
//        } else {
//          phoneBuilder_.remove(index);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder getPhoneBuilder(
//          int index) {
//        return getPhoneFieldBuilder().getBuilder(index);
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(
//          int index) {
//        if (phoneBuilder_ == null) {
//          return phone_.get(index);  } else {
//          return phoneBuilder_.getMessageOrBuilder(index);
//        }
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public java.util.List<? extends com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder>
//           getPhoneOrBuilderList() {
//        if (phoneBuilder_ != null) {
//          return phoneBuilder_.getMessageOrBuilderList();
//        } else {
//          return java.util.Collections.unmodifiableList(phone_);
//        }
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder addPhoneBuilder() {
//        return getPhoneFieldBuilder().addBuilder(
//            com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.getDefaultInstance());
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder addPhoneBuilder(
//          int index) {
//        return getPhoneFieldBuilder().addBuilder(
//            index, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.getDefaultInstance());
//      }
//      /**
//       * <code>repeated .Student.PhoneNumber phone = 5;</code>
//       */
//      public java.util.List<com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder>
//           getPhoneBuilderList() {
//        return getPhoneFieldBuilder().getBuilderList();
//      }
//      private com.google.protobuf.RepeatedFieldBuilderV3<
//          com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder>
//          getPhoneFieldBuilder() {
//        if (phoneBuilder_ == null) {
//          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
//              com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumber.Builder, com.fish.protobuf.entity.ProtoDemo.Student.PhoneNumberOrBuilder>(
//                  phone_,
//                  ((bitField0_ & 0x00000010) != 0),
//                  getParentForChildren(),
//                  isClean());
//          phone_ = null;
//        }
//        return phoneBuilder_;
//      }
//      @java.lang.Override
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFields(unknownFields);
//      }
//
//      @java.lang.Override
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:Student)
//    }
//
//    // @@protoc_insertion_point(class_scope:Student)
//    private static final com.fish.protobuf.entity.ProtoDemo.Student DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new com.fish.protobuf.entity.ProtoDemo.Student();
//    }
//
//    public static com.fish.protobuf.entity.ProtoDemo.Student getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<Student>
//        PARSER = new com.google.protobuf.AbstractParser<Student>() {
//      @java.lang.Override
//      public Student parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        Builder builder = newBuilder();
//        try {
//          builder.mergeFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          throw e.setUnfinishedMessage(builder.buildPartial());
//        } catch (com.google.protobuf.UninitializedMessageException e) {
//          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
//        } catch (java.io.IOException e) {
//          throw new com.google.protobuf.InvalidProtocolBufferException(e)
//              .setUnfinishedMessage(builder.buildPartial());
//        }
//        return builder.buildPartial();
//      }
//    };
//
//    public static com.google.protobuf.Parser<Student> parser() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<Student> getParserForType() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.fish.protobuf.entity.ProtoDemo.Student getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_Student_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_Student_fieldAccessorTable;
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_Student_PhoneNumber_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_Student_PhoneNumber_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    java.lang.String[] descriptorData = {
//      "\n\017ProtoDemo.proto\"\373\001\n\007Student\022\n\n\002id\030\001 \001(" +
//      "\005\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\031\n\003sex\030\004 " +
//      "\001(\0162\014.Student.Sex\022#\n\005phone\030\005 \003(\0132\024.Stude" +
//      "nt.PhoneNumber\032?\n\013PhoneNumber\022\016\n\006number\030" +
//      "\001 \001(\t\022 \n\004type\030\002 \001(\0162\022.Student.PhoneType\"" +
//      "\031\n\003Sex\022\007\n\003MAN\020\000\022\t\n\005WOMAN\020\001\"+\n\tPhoneType\022" +
//      "\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002B%\n\030com.f" +
//      "ish.protobuf.entityB\tProtoDemob\006proto3"
//    };
//    descriptor = com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        });
//    internal_static_Student_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_Student_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_Student_descriptor,
//        new java.lang.String[] { "Id", "Name", "Email", "Sex", "Phone", });
//    internal_static_Student_PhoneNumber_descriptor =
//      internal_static_Student_descriptor.getNestedTypes().get(0);
//    internal_static_Student_PhoneNumber_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_Student_PhoneNumber_descriptor,
//        new java.lang.String[] { "Number", "Type", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
